### ISSUE TITLE
Add the AddressFamily variable

### ISSUE THREAD

**Issue by Andrew415** [debops/ansible-sshd#31]
Hi,

I would like to have a default variable added for AddressFamily interfaces. At present the only option is "sshd__listen: []" which sounds like it is intended to be run on a single server or added per server:

"# List of IP addresses on which `sshd` should listen for new connections. If it's empty, `sshd` listens on all interfaces."

Although that is fine for a single host, I would like to fine tune network access by IP protocol such as the sshd options:

AddressFamily any # default
AddressFamily inet # IPv4 only
AddressFamily inet6 # IPv6 only

In my use case for example, ipv6 for ssh is not supported and allowing sshd to listen on ipv6 interfaces that should not be up in the first place increases the risk of unauthorized backdoor access. If wanted I can make a pull request for this change.

**Comment by drybjed** [comment]
Sure, sounds good. You can go ahead with the PR.

NB, if you don't know, `debops.ferm` is IPv4/IPv6-aware. If you set only IPv4 subnets in `sshd__allow` and use `debops.ferm` to manage the firewall and pass the configuration from `debops.sshd`, firewall will be opened on `22/tcp` only to IPv4 network, not IPv6.

**Comment by drybjed** [comment]
The `AddressFamily` parameter can be set using the `sshd__custom_options` variable (YAML text block). I'm closing this issue for now, if there's an interest for more automated `AddressFamily` management using a separate variable, let me know.
