### ISSUE TITLE
Add sshd_gateway_ports variable

### ISSUE THREAD

**Issue by tallandtree** [debops/ansible-sshd#45]
Add to templates/etc/sshd/sshd_config.j2 template the possibility to set GatewayPorts to yes.
Default value of sshd_gateway_ports should be 'no'.

This allows you to setup an ssh tunnel.
I can implement this.

**Comment by tallandtree** [comment]
Please forget it. I'll use sshd__custom_options.

**Comment by ypid** [comment]
> Default value of sshd_gateway_ports should be 'no'.

When I last checked, the default value of this option in sshd is compiled-in 'no'. I guess the `sshd__custom_options` which you already found should be a good fit if you want to change that. Here is my usage of this: https://github.com/ypid/ypid-ansible-inventory/blob/master/group_vars/all/public_debops_common/public_paranoid_debops_sshd.yml
