### ISSUE TITLE
No way to allow connections from all hosts

### ISSUE THREAD

**Issue by bfabio** [debops/ansible-sshd#50]
There is no way to allow the connection to ssh to everyone, unless I'm missing something.

`sshd__allow` is used for both ferm (https://github.com/debops/ansible-sshd/blob/master/defaults/main.yml#L628), which expects an IP and /etc/hosts.allow, which can deal with IPs and other patterns (fe. wildcards or NIS netgroup names).

One would think 0.0.0.0/0 represents any hosts in both configurations, but it looks like it doesn't. Ferm has no problem with it, unlike tcp-wrappers: the expected result is achieved by using "ALL" in hosts.allow.

**Comment by drybjed** [comment]
By default `debops.sshd` should configure `debops.ferm` to allow rate-limited connections to SSH from anywhere. You can disable the rate-limiting completely by setting `sshd__ferm_limit` but as I look now, it won't let you open up the SSH service completely.

Right now I'm working on revamped `debops.ferm` role, after that it should be easier to modify dependent rules through the inventory if needed.

**Comment by bfabio** [comment]
Oh, right I didn't notice `sshd__tcpwrappers_default: ALL`.

I think `sshd__allow: ALL` was required with an old version, but it's not anymore.

**Comment by drybjed** [comment]
@bfabio There's also a set of `sshd__*_whitelist` variables which allow you to specify hosts which should be allowed to connect to the SSH server without any restrictions, but adding hosts there will not block the access to SSH from other hosts, unlike `sshd__*_allow` does.

**Comment by drybjed** [comment]
The issue seems to be resolved, so I'm closing it.
