### ISSUE TITLE
unable to resolve host, EC2 fail

### ISSUE THREAD

**Issue by cyrrill** [debops/ansible-sshd#58]
A new Ubuntu 16.04 server fails as follows:

TASK [debops.authorized_keys : Configure authorized keys for users] ******************************************************************

TASK [debops.authorized_keys : Enforce state of authorized_keys user files] **********************************************************

TASK [debops.secret : Create secret directories on Ansible Controller] ***************************************************************

TASK [debops.sshd : Pre hooks] *******************************************************************************************************

TASK [debops.sshd : Check if OpenSSH is installed (or half-installed)] ***************************************************************
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in version 2.4. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [34.207.30.127]: FAILED! => {"changed": false, "failed": true, "failed_when_result": true, "rc": 0, "stderr": "Shared connection to XX.XX.XX.XX closed.\r\n", "stdout": "sudo: unable to resolve host ip-10-0-0-116\r\ninstalled\r\n", "stdout_lines": ["**sudo: unable to resolve host ip-10-0-0-116**", "installed"]}

**Comment by cyrrill** [comment]
I have a few follow questions if possible:

If I log into the host in question, I see that calling `sudo` on any other command, issues the same warning. It's possible to fix it by adding an entry to `/etc/hosts` with the ip.

A) How can I gather this "ip-10-0-0-116" prior to running this role, so that I may include it into `/etc/hosts` ?
 
Interestingly enough, this DNS warning does exit or fail other programs, it just appends the warning via stdout, but the command still runs. For example:
```
-------------------------------------------------
        This system is managed by Ansible
-------------------------------------------------
Last login: Tue Apr 18 04:16:58 2017 from X.X.X.X
ubuntu@ip-10-0-0-116:~$ sudo date
sudo: unable to resolve host ip-10-0-0-116
Tue Apr 18 04:30:18 UTC 2017
ubuntu@ip-10-0-0-116:~$
```

B) It seems like SSH ansible role is being too sensitive to an innocous warning? Should the default behaviour be to ignore these minor issues and proceed? or is failing and exiting the more correct thing to do?

C) Is it possible to ignore these warnings? Even if not a change in the general repo, I'd like to know how for other cases. Once I can add the entry to `/etc/hosts` there should be no more issue.

**Comment by cyrrill** [comment]
For A), looks like this works?
echo "127.0.0.1 $(hostname)" >> /etc/hosts

I see this is an old issue at AWS:
https://forums.aws.amazon.com/message.jspa?messageID=495274

**Comment by drybjed** [comment]
@cyrrill You could try and use the [debops.bootstrap](https://docs.debops.org/en/latest/ansible/roles/ansible-bootstrap/docs/index.html) role to prepare the host for Ansible management. It has an option to [add a hostname and FQDN to the /etc/hosts file](https://docs.debops.org/en/latest/ansible/roles/ansible-bootstrap/docs/defaults.html#hostname-and-domain) that could add the missing entry for you.

I don't think that we can solve the warning issue from DebOps, that would need to be done in Ansible. Still, fixing the DNS issue (it's always DNS) is probably the best solution overall.

**Comment by stonecold123** [comment]
@drybjed 
I'm getting the same error in a server that is missing the host name in /etc/hosts.
I've solved this problem before I found debops by adding `127.0.1.1   mynode-30000` to the file.

How can I add that line to /etc/hosts during the debops bootstrap?

I add a variable `bootstrap__hostname: '127.0.1.1   mynode-30000'`
but it says 

````
fatal: [myserver]: FAILED! => {"changed": false, "failed": true,
"msg": "Command failed rc=1, out=, err=Could not set property: Invalid hostname '127.0.1.1   mynode-30000'\n"}
````
