### ISSUE TITLE
Stretch issue: missing packages

### ISSUE THREAD

**Issue by bjornoss** [debops/ansible-sshd#61]
Installation report
The role fails on stretch because the following packages is not available anymore: 
'openssh-blacklist', 'openssh-blacklist-extra' 

Source: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=859682

Fix: sshd__recommended_packages: [ ]

**Comment by ypid** [comment]
Fixed by: #57 (not yet merged)

**Comment by ypid** [comment]
Fixed by: #59 (merged)

**Comment by ypid** [comment]
Working on Stretch without issues for some time now. Can be closed.
