### ISSUE TITLE
List of MAC algorithms broken for openssh 7.6

### ISSUE THREAD

**Issue by javiplx** [debops/ansible-sshd#63]
The stock openssh version of ubuntu bionic is not compatible with this role. Release 7.6 [dropped support for hmac-ripemd160](https://www.openssh.com/txt/release-7.6), and looking at the code for `templates/etc/ssh/sshd_config.j2` it seems only capable to increase the supportec MACs but not to remove a dropped one.

**Comment by drybjed** [comment]
Thanks for reporting this issue! Can you check if the version in [DebOps monorepo](https://github.com/debops/debops/) also has the same problem? The main development is now done in the monorepo.

**Comment by javiplx** [comment]
I've pasted the relevant part of the template and seems to work properly.
Should I understand that the "standalone" versions of the roles are deprecated and we should clone the monorepo repository instead?

**Comment by drybjed** [comment]
Yes. Unfortunately current usage via Ansible Galaxy seems to be horribly broken, so your best bet is to just clone the repo itself and add the `ansible/roles/` subdirectory in your Ansible's `ansible.cfg` configuration file `roles_path` parameter.
